//under {NAME} in makefile
				@echo "$(COLOUR_VIO)      ___          ___          ___          ___              $(COLOUR_END)"
				@echo "$(COLOUR_VIO)     /\  \        /\  \        /\__\        /\  \             $(COLOUR_END)"
				@echo "$(COLOUR_VIO)    /::\  \      /::\  \      /::|  |      /::\  \            $(COLOUR_END)"
				@echo "$(COLOUR_VIO)   /:/\:\  \    /:/\:\  \    /:|:|  |     /:/\:\  \           $(COLOUR_END)"
				@echo "$(COLOUR_VIO)  /:/  \:\__\  /:/  \:\  \  /:/|:|  |__  /::\~\:\  \          $(COLOUR_END)"
				@echo "$(COLOUR_VIO) /:/__/ \:|__|/:/__/ \:\__\/:/ |:| /\__\/:/\:\ \:\__\         $(COLOUR_END)"
				@echo "$(COLOUR_VIO) \:\  \ /:/  /\:\  \ /:/  /\/__|:|/:/  /\:\~\:\ \/__/         $(COLOUR_END)"
				@echo "$(COLOUR_VIO)  \:\  /:/  /  \:\  /:/  /     |:/:/  /  \:\ \:\__\           $(COLOUR_END)"
				@echo "$(COLOUR_VIO)   \:\/:/  /    \:\/:/  /      |::/  /    \:\ \/__/           $(COLOUR_END)"
				@echo "$(COLOUR_VIO)    \::/  /      \::/  /       /:/  /      \:\__\             $(COLOUR_END)"
				@echo "$(COLOUR_VIO)     \/__/        \/__/        \/__/        \/__/$(COLOUR_END)"
